"""
Data Models for Project Sentinel
COMPLETE: Includes all required enums and models
"""

from pydantic import BaseModel, Field
from datetime import datetime
from typing import List, Optional
from enum import Enum

# ============================================
# ENUMS
# ============================================

class Severity(str, Enum):
    """Alert severity levels"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"

class ThreatType(str, Enum):
    """Types of public health threats"""
    WATERBORNE = "waterborne"
    AIRBORNE = "airborne"
    FOODBORNE = "foodborne"
    VECTOR = "vector_borne"
    UNKNOWN = "unknown"

# ============================================
# INPUT MODELS
# ============================================

class HealthDataPoint(BaseModel):
    """
    Health data point for ingestion
    """
    timestamp: str = Field(..., description="ISO 8601 timestamp")
    zone_id: str = Field(..., description="Mumbai zone identifier")
    data_type: str = Field(..., description="Type of health data")
    value: float = Field(..., description="Measurement value")
    latitude: float = Field(..., description="Latitude coordinate")
    longitude: float = Field(..., description="Longitude coordinate")
    
    class Config:
        json_schema_extra = {
            "example": {
                "timestamp": "2024-11-29T05:30:00",
                "zone_id": "Bandra",
                "data_type": "water_quality",
                "value": 7.5,
                "latitude": 19.0596,
                "longitude": 72.8295
            }
        }

# ============================================
# OUTPUT MODELS
# ============================================

class ThreatAlert(BaseModel):
    """
    Threat alert generated by Sentinel Agent
    """
    alert_id: str = Field(..., description="Unique alert identifier")
    timestamp: datetime = Field(..., description="Alert generation time")
    threat_type: ThreatType = Field(..., description="Type of threat")
    severity: Severity = Field(..., description="Severity level")
    confidence: float = Field(..., description="ML confidence score (0-100)")
    affected_zones: List[str] = Field(..., description="List of affected zones")
    description: str = Field(..., description="Detailed threat description")
    recommendations: List[str] = Field(..., description="Recommended actions")
    data_sources: List[str] = Field(..., description="Data types contributing to alert")
    anomaly_count: int = Field(..., description="Number of anomalies detected")
    notifications_sent: List[str] = Field(default_factory=list, description="Notification channels used")
    
    class Config:
        json_schema_extra = {
            "example": {
                "alert_id": "a7f3e92b-4d21-4c5f-9f8e-2a3b1c5d7e9f",
                "timestamp": "2024-11-29T05:35:00",
                "threat_type": "waterborne",
                "severity": "high",
                "confidence": 89.5,
                "affected_zones": ["Bandra"],
                "description": "Potential waterborne contamination outbreak detected in Bandra.",
                "recommendations": [
                    "Deploy rapid response team to Bandra",
                    "Test water supply systems for contamination"
                ],
                "data_sources": ["water_quality", "pharmacy_sales", "hospital_visits"],
                "anomaly_count": 3,
                "notifications_sent": ["SMS", "WhatsApp"]
            }
        }

class DetectionResult(BaseModel):
    """
    Detection result from ML models
    """
    is_anomaly: bool = Field(..., description="Whether anomaly was detected")
    confidence: float = Field(..., description="Detection confidence (0-100)")
    votes: int = Field(..., description="Number of models voting anomaly")
    total_models: int = Field(..., description="Total models in ensemble")
    detection_details: dict = Field(..., description="Per-model detection details")
    threshold_met: bool = Field(..., description="Whether ensemble threshold was met")

